import { SanitizationReport } from "../types";

export function generateTextReport(
  report: SanitizationReport,
  includeValues: boolean = false
): string {
  const lines: string[] = [];

  lines.push("=================================================");
  lines.push("          CLEANFILE SANITIZATION REPORT          ");
  lines.push("=================================================");
  lines.push("");
  lines.push(`Report ID:          ${report.reportId}`);
  lines.push(`File Name:          ${report.fileName}`);
  lines.push(`File Size:          ${(report.fileSize / 1024).toFixed(1)} KB`);
  lines.push(`File Format:        ${report.format}`);
  lines.push(`Timestamp:          ${report.processingTimestamp}`);
  lines.push(`Verification:       ${report.verificationStatus}`);
  lines.push("");
  lines.push("-------------------------------------------------");
  lines.push("              PRIVACY SCORE ANALYSIS             ");
  lines.push("-------------------------------------------------");
  lines.push(`Score Before:       ${report.beforeScore} / 100 (${report.beforeRiskLevel} RISK)`);
  lines.push(`Score After:        ${report.afterScore} / 100 (${report.afterRiskLevel} RISK)`);
  lines.push(`Score Delta:        +${report.afterScore - report.beforeScore} points`);
  lines.push("");
  lines.push("-------------------------------------------------");
  lines.push("                FINDINGS SUMMARY                 ");
  lines.push("-------------------------------------------------");
  lines.push(`Total Detected:     ${report.totalFindings}`);
  lines.push(`Successfully Removed: ${report.removedCount}`);
  lines.push(`Remaining / Unremoved: ${report.remainingCount}`);
  lines.push("");
  lines.push("-------------------------------------------------");
  lines.push("                DETAILED FINDINGS                ");
  lines.push("-------------------------------------------------");

  if (report.findings.length === 0) {
    lines.push("No removable metadata fields were detected in this file.");
  } else {
    for (const f of report.findings) {
      const status = f.removed ? "[REMOVED]" : "[REMAINING]";
      const severity = f.severity.toUpperCase();
      lines.push(`${status} [${severity}] ${f.field} (${f.category})`);
      if (includeValues && f.value) {
        lines.push(`   Value: ${f.value}`);
      }
      if (!f.removed && f.limitation) {
        lines.push(`   Reason: ${f.limitation}`);
      }
    }
  }

  lines.push("");
  lines.push("-------------------------------------------------");
  lines.push("              FORMAT LIMITATIONS                 ");
  lines.push("-------------------------------------------------");
  for (const lim of report.limitations) {
    lines.push(`- ${lim}`);
  }

  lines.push("");
  lines.push("-------------------------------------------------");
  lines.push("                  DISCLAIMER                     ");
  lines.push("-------------------------------------------------");
  lines.push(report.disclaimer);
  lines.push("");
  lines.push("=================================================");
  lines.push("    Generated by CleanFile (https://cleanfile.app)");
  lines.push("=================================================");

  return lines.join("\n");
}
